version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  build:
    commands:
      - aws cloudformation package --s3-bucket $LAMBDA_ARTIFACT_STORE_BUCKET --template-file template.yml --output-template-file output-template.yml

artifacts:
  files:
    - template.yml
    - output-template.yml
