version: 0.2

phases:
  install:
    commands:
      - npm ci
      - npm run build
  build:
    commands:
      - aws cloudformation package --s3-bucket $LAMBDA_ARTIFACT_STORE_BUCKET --template-file template.yml --output-template-file output-template.yml

artifacts:
  type: zip
  files:
    - template.yml
    - output-template.yml
